# Generated by Django 5.2 on 2025-05-03 19:51

import django.db.models.deletion
import tournament.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Torneo')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Curso'), ('completed', 'Finalizado')], default='pending', max_length=20, verbose_name='Estado')),
                ('mode', models.CharField(choices=[('classical', 'Clásico (>60 min)'), ('rapid', 'Rápido (10-60 min)'), ('blitz', 'Blitz (3-10 min)'), ('bullet', 'Bala (<3 min)'), ('hyperbullet', 'Ultrabala (30 seg)')], default='classical', max_length=200, verbose_name='Modo')),
                ('prize', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Premio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=tournament.models.generate_uuid, max_length=200, unique=True, verbose_name='Código del Torneo')),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournament.tournament', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'unique_together': {('tournament', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=50, unique=True, verbose_name='ID de Partida')),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('in_progress', 'En Curso'), ('completed', 'Finalizado')], default='scheduled', max_length=20, verbose_name='Estado')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Inicio')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Finalización')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to='tournament.participant', verbose_name='Jugador 1')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to='tournament.participant', verbose_name='Jugador 2')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='tournament.participant', verbose_name='Ganador')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.tournament', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
    ]
