# Generated by Django 5.2 on 2025-05-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='elo',
            field=models.IntegerField(default=1000, verbose_name='Elo'),
        ),
        migrations.AddField(
            model_name='participant',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Puntos'),
        ),
    ]
